#!/usr/bin/env python3
"""Build only the marked README region and references.bib; no network or dependencies."""
import argparse
import difflib
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
START = '<!-- BEGIN GENERATED CATALOG -->'
END = '<!-- END GENERATED CATALOG -->'


def cell(value):
    return str(value).replace('|', '&#124;').replace('\n', ' ').replace('<', '&lt;').replace('>', '&gt;')


def link(label, url):
    return f'[{cell(label)}]({url})'


def catalog(records):
    scopes = [('core', 'Core methods'), ('supporting', 'Core supporting resources'),
              ('adjacent', 'Related but distinct')]
    out = ['## Catalog', '', 'Generated from [data/resources.json](data/resources.json). '
           'Dates below are source checks, not a claim of exhaustive coverage.']
    out += ['', '| Scope | Papers | Other resources |', '| --- | ---: | ---: |']
    for scope, title in scopes:
        group = [r for r in records if r['scope'] == scope]
        papers = sum(r['resource_type'] == 'paper' for r in group)
        out.append(f'| {title} | {papers} | {len(group) - papers} |')
    dates = sorted({r['verified_on'] for r in records})
    out += ['', f"Per-record verification dates: {', '.join(dates)}. "
            'Related resource records are not counted as additional papers.', '', '## Start here', '',
            'One possible route, chosen for contrasting questions rather than priority or rank:', '']
    for r in sorted((r for r in records if r.get('reading_order')), key=lambda r:r['reading_order']):
        out.append(f"- {link(r.get('short_name', r['title']), '#'+r['id'])}: {r['reading_reason']}")
    for scope, heading in scopes:
        out += ['', f'## {heading}', '', '| Work | Year / status | Signal; mechanism | Official resources | Contribution / boundary |',
                '| --- | --- | --- | --- | --- |']
        for r in sorted((r for r in records if r['scope'] == scope), key=lambda r:(r.get('first_publication_date') or '',r['id']), reverse=True):
            status = (f"{r['publication_year']} · {r['venue'] or 'arXiv'} · {r['publication_status']}"
                      if r['resource_type']=='paper' else r['resource_type'])
            resources = []
            for field, label in [('official_code_url', 'Code'), ('project_url', 'Project'), ('data_url', 'Data'), ('model_url', 'Model')]:
                if r.get(field): resources.append(link(label,r[field]))
            if r.get('code_status') in ('not_found','announced','unverified'):
                resources.append(f"Code: Not found as of {r['verified_on']}" if r['code_status']=='not_found' else f"Code: {r['code_status']}")
            if r.get('code_status') in ('partial','inaccessible'):resources.append(f"({r['code_status']})")
            signal = '; '.join(', '.join(t.replace('_', ' ') for t in r[k]) for k in ['user_signals','methods'] if r[k])
            out.append(f"| <a id=\"{r['id']}\"></a>{link(r['title'],r['primary_url'])} | {cell(status)} | {cell(signal)} | {' · '.join(resources) or 'See primary source'} | {cell(r['summary'])} |")
    out += ['', '## Datasets and benchmarks', '',
            'These descriptions summarize the verified releases or paper protocols; a real-user history '
            'does not by itself imply a target-user generation study. Access and licenses belong to the providers.', '',
            '| Resource / parent paper | User IDs and feedback | Origin | Reported size (units explicit) | Evaluation / access caveat |',
            '| --- | --- | --- | --- | --- |']
    for r in records:
        d = r.get('dataset_details')
        if d:
            out.append(f"| {link(d['name'],'#'+r['id'])} | {cell(d['user_identity'])}; {cell(d['feedback'])} | {d['origin']} | {cell(d['size_note'])} | {cell(d['evaluation_note'])} |")
    out += ['', 'Metadata, source-level dates, split evidence, verified base models, limitations and conflicts '
            'are preserved in [the JSON catalog](data/resources.json). No cross-protocol leaderboard is maintained.', '']
    return '\n'.join(out)


def bib_escape(text):
    mapping = {'\\':r'\textbackslash{}', '&':r'\&', '%':r'\%', '_':r'\_', '#':r'\#', '$':r'\$', '{':r'\{', '}':r'\}'}
    return ''.join(mapping.get(c,c) for c in str(text))


def bibliography(records):
    out = ['% Generated by scripts/build.py from data/resources.json. Do not edit.',
           '% Minimal verified metadata; absent DOI/pages are deliberately omitted.', '']
    for r in sorted(records, key=lambda r:r['id']):
        b = r.get('bibtex')
        if r['resource_type'] != 'paper' or b is None: continue
        fields = [('title', '{'+bib_escape(r['title'])+'}'),
                  ('author', bib_escape(' and '.join(r['authors']))), ('year', str(r['publication_year']))]
        if b.get('container'):
            fields.append(('booktitle' if b['entry_type']=='inproceedings' else 'journal',bib_escape(b['container'])))
        if b.get('pages'): fields.append(('pages', b['pages']))
        if r['publication_status']=='accepted':fields.append(('note',bib_escape('Accepted at '+r['venue']+'; proceedings not verified')))
        if r.get('arxiv_id'):fields += [('eprint',r['arxiv_id']),('archivePrefix','arXiv')]
        if r.get('doi'): fields.append(('doi',r['doi']))
        fields.append(('url',r['primary_url']))
        out.append('@'+b['entry_type']+'{'+b['key']+',')
        out += [f'  {key} = {{{value}}},' for key,value in fields]
        out += ['}', '']
    return '\n'.join(out)


def outputs(root=ROOT):
    records = json.loads((root/'data/resources.json').read_text(encoding='utf-8'))['resources']
    original = (root/'README.md').read_text(encoding='utf-8')
    if original.count(START)!=1 or original.count(END)!=1 or original.index(START)>original.index(END):
        raise ValueError('README must contain exactly one ordered pair of generated markers')
    before = original.split(START)[0]
    after = original.split(END)[1]
    readme = before+START+'\n\n'+catalog(records)+'\n'+END+after
    return {'README.md':readme,'references.bib':bibliography(records)}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true',help='Fail on stale outputs without writing files')
    args = parser.parse_args()
    try: generated=outputs()
    except (OSError, ValueError, KeyError, TypeError) as exc:
        print(f'Build error: {exc}',file=sys.stderr);return 1
    stale=[]
    for name,expected in generated.items():
        path=ROOT/name
        actual=path.read_text(encoding='utf-8') if path.exists() else ''
        if actual!=expected:
            stale.append(name)
            if args.check:
                print(''.join(difflib.unified_diff(actual.splitlines(True),expected.splitlines(True),fromfile=name,tofile=name+' (generated)'))[:6000])
            else:path.write_text(expected,encoding='utf-8')
    if args.check and stale:
        print('Stale generated files: '+', '.join(stale),file=sys.stderr);return 1
    print('Generated files are up to date.' if args.check else 'Built README.md and references.bib.')
    return 0

if __name__=='__main__':sys.exit(main())
